### ISSUE TITLE
Apply Post-Toronto edits

### ISSUE THREAD

**Issue by CaseyCarter** [ericniebler/stl2#455]
### P0663 "Ranges TS 'Ready' Issues for Toronto"
- [X] 155: Comparison concepts and reference types; depends on: #167.
- [X] 172: tagged<Base...> should be implicitly constructible from Base
- [X] 203: Don’t slurp entities from std into std::experimental::ranges::v1
- [X] 232: Kill the Readability requirement for i++ for InputIterators
- [X] 235: Trivial example breaks common_type from P0022
- [X] 245: The iterator adaptors should customize iter_move and iter_swap
- [X] 251: algorithms incorrectly specified in terms of swap(*a,*b) instead iter_swap(a,b), and move(*a) instead of iter_move(a)
- [X] 259: is_swappable type traits should not be in namespace std
- [X] 286: Resolve inconsistency in indirect_result_of
- [X] 288: “regular function” != RegularInvocable
- [X] 299: value_type of classes with member element_type
- [X] 302: insert_iterator and ostreambuf_iterator don’t properly support *o++ = t;
- [X] 307: Incomplete edit to InputIterator to support proxy iterators
- [X] 309: Missing “Returns:” clause of sort/stable_sort/partial_sort/nth_element
- [X] 311: Common and CommonReference should use ConvertibleTo to test for implicit convertibility
- [X] 316: copy_if “Returns” clause incorrect
- [X] 317: is_nothrow_indirectly_movable could be true even when iter_move is noexcept(false)
- [X] 318: common_iterator::operator-> does not specify its return type
- [X] 321: Concepts that use type traits are inadvertently subsuming them; depends on: #255, #167.
- [x] 330: Argument deduction constraints are specified incorrectly; depends on P0547, #155 
- [x] 331: Reorder requirements in concept Iterator
- [x] 345: US 2 (006): 2.1.1: Update ranged-for-loop wording
- [x] 354: JP 1 (015): 6.9.2.2/1: Range doesn’t require begin
- [x] 357: JP 3 (018): 7.4.4/5: transform does not include projection calls in Complexity

### P0740 "Ranges TS 'Immediate' Issues from Toronto"
- [x] 61: Review stated complexities of algorithms wrt the use of projections
- [x] 70: Why do neither reference types nor array types satisfy Destructible?
- [x] 154: Raw pointer does not satisfy the requirements of RandomAccessIterator
- [x] 156: Validity of references obtained from out-of-lifetime iterators
- [X] 167: `ConvertibleTo` should require both implicit and explicit conversion; also fixes #314
- [x] 170: unique_copy and LWG 2439
- [x] 174: Swappable concept and P0185 swappable traits
- [x] 176: Relax requirements on replace and replace_if
- [X] 211: Add new header <experimental/range/range>
- [x] 229: Assignable concept looks wrong
- [x] 250: Do common_iterator’s copy/move ctors/operators need to be specified?
- [X] 255: DerivedFrom should be “publicly and unambiguously”
- [x] 256: Add constexpr to advance, distance, next, and prev
- [x] 261: Restrict alg.general changes from P0370 to apply only to the range-and-a-half algorithms
- [x] 262: Use expression-equivalent in definitions of CPOs
- [x] 284: iter_move and iter_swap need to say when they are noexcept and constexpr
- [x] 289: [iterator, count) ranges
- [x] 298: common_iterator::operator-> with xvalue operator*
- [x] 300: Is it intended that an aggregate with a deleted or nonexistent default constructor satisfy DefaultConstructible?
- [x] 301: Is it intended that Constructible<int&, long&>() is true?
- [x] 310: Movable<int&&>() is true and it should probably be false
- [x] 313: MoveConstructible<T>() != std::is_move_constructible<T>()
- [X] 314: `ConvertibleTo<T&&, U>` should say something about the final state of the source object [fixed by #167]
- [x] 322: ranges::exchange should be constexpr and conditionally noexcept
- [x] 338: common_reference doesn’t work with some proxy references
- [x] 339: After P0547R0, const-qualified iterator types are not Readable or Writable
- [x] 340: GB 1 (001): Consider all outstanding issues before the final TS is produced
- [x] 361: P0541 is missing semantics for OutputIterator’s writable post-increment result
- [x] 366: common_iterator::operator-> is underconstrained
- [x] 367: advance, distance, next, and prev should be customization point objects
- [x] 368: common_iterator’s and counted_iterator’s const operator* need to be constrained
- [X] 379: Switch to variable concepts
- [x] 381: Readable types with prvalue reference types erroneously model Writable
- [x] 382: Don’t try to forbid overloaded & in Destructible
- [x] 386: P0541: basic exception guarantee in counted_iterator’s postincrement
- [x] 387: Writable should work with rvalues
- [x] 396: SizedRange should not require size() to be callable on a const qualified object
- [x] 398: Assignable semantic constraints contradict each other for self-assign
- [x] 399: iterators that return move-only types by value do not satisfy Readable
- [x] 404: Normative content in informative subclause
- [x] 407: istreambuf_iterator::operator->
- [X] 411: find_first_of and mismatch should use IndirectRelation instead of Indirect(Binary)Predicate
- [x] 414: Remove is_[nothrow]_indirectly_(movable|swappable); depends on: 284
- [x] 420: Harmonize common_type with C++17’s [meta.trans.other]/p4
- [x] 421: With common_type, the Ranges TS requires vendors to break conformance
- [x] 424: Constrain return types in IndirectInvocable
- [x] 436: common_iterator’s destructor should not be specified in [common.iter.op=]

### Other
- [x] Fixup line wrapping throughout. Especially check `Assignable` and `Destructible`.
- [x] Do a complete pass looking for `()` that managed to sneak in after applying P0651.
- [x] Determine "fancy" cover page requirements for the final TS document

**Comment by CaseyCarter** [comment]
@cjdb has  331, 354, and 357.

**Comment by CaseyCarter** [comment]
Fixup line wrapping in `Assignable` and `Destructible`.

**Comment by CaseyCarter** [comment]
Do a complete pass looking for `()` that managed to sneak in after applying P0651.

**Comment by CaseyCarter** [comment]
Marking #174 complete, despite that there are now no changes to make. I think the PR was incorporated into P0547R2 and we failed to record that fact.

**Comment by CaseyCarter** [comment]
Address #471 "`IndirectRelation` should introduce a consistent parameter name."

**Comment by CaseyCarter** [comment]
Ditto marking #298 complete; it seems to have been fixed somewhere along the way.

**Comment by CaseyCarter** [comment]
..and #361, which I think was pulled into P0541.

**Comment by CaseyCarter** [comment]
Needs formatting cleanup:
* [structure.requirements]/7
* [contents]/2
